docs: Adds coder_git_auth deprication notice (#203)
coder/terraform-provider-coder pull request #214
Opened 2024-04-26 18:19 UTC by kyle-pazdel

Adds deprication notice to git_auth in docs and renames 'gh' to 'GitHub' in external_auth docs for clarity.

2024-04-26 19:34 UTC, kyle-pazdel commented
I have read the CLA Document and I hereby sign the CLA
recheck

2024-04-26 19:35 UTC, kyle-pazdel commented
recheck

2024-04-27 08:29 UTC, matifali commented on docs/data-sources/external_auth.md
> -  Use this data source to require users to authenticate with an external service prior to workspace creation. This can be used to pre-authenticate external services in a workspace. (e.g. gcloud, gh,
`gcloud`, `gh` and `docker` are the binary names. IMO, `gh` makes better sense.

2024-04-27 08:37 UTC, matifali requested changes
docs are generated files so we should update the description in the go code,
for example,
https://github.com/coder/terraform-provider-coder/blob/8c5e8ff9579d1d766d5317422bf3c1988b710434/provider/gitauth.go#L16

2024-07-02 14:56 UTC, matifali commented
Can be closed if we do #250.

2024-07-02 14:56 UTC, closed without merging